[phases.setup]
nixPkgs = ["jdk17"]

[phases.install]
cmds = ["mvn clean package -DskipTests"]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "java -jar target/realtime-chat-1.0.0.jar"
